# Workflow name
name: Python CI

# Trigger the workflow on push and pull request events
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# A single job named 'test'
jobs:
  test:
    # Use the latest Ubuntu runner
    runs-on: ubuntu-latest

    # Strategy to test with different Python versions (optional but good practice)
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    # Steps to run within the 'test' job
    steps:
    # Step 1: Check out the repository code
    - uses: actions/checkout@v4

    # Step 2: Set up a specific Python version
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    # Step 3: Install dependencies from requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run the automated tests with pytest
    - name: Run tests with pytest
      run: |
        pytest
